# Generated by Django 2.1.4 on 2018-12-17 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import instagrams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=100, verbose_name='내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to=instagrams.models.get_instagram_photo_path, verbose_name='사진')),
                ('instagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='instagrams.Instagram', verbose_name='인스타그램')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
