# Generated by Django 2.0.6 on 2018-12-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100, verbose_name='내용'),
        ),
    ]
